# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metric_record.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='metric_record.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13metric_record.proto\"\x95\x04\n\x0cMetricRecord\x12@\n\x14timeSeriesDescriptor\x18\x01 \x01(\x0b\x32\".MetricRecord.Timeseriesdescriptor\x12*\n\tpointData\x18\x02 \x01(\x0b\x32\x17.MetricRecord.Pointdata\x12\x12\n\nmetricName\x18\x03 \x01(\t\x1a\xb4\x01\n\x14Timeseriesdescriptor\x12\x16\n\x0e\x63ontainer_name\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x14\n\x0c\x63luster_name\x18\x04 \x01(\t\x12\x16\n\x0enamespace_name\x18\x05 \x01(\t\x12\x17\n\x0f\x63ontroller_name\x18\x06 \x01(\t\x12\x17\n\x0f\x63ontroller_type\x18\x07 \x01(\t\x1a\x34\n\x0cTimeinterval\x12\x12\n\nstart_time\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\t\x1a\x31\n\x06Values\x12\x12\n\nint64Value\x18\x01 \x01(\x03\x12\x13\n\x0b\x64oubleValue\x18\x02 \x01(\x01\x1a\x63\n\tPointdata\x12\x30\n\x0ctimeInterval\x18\x01 \x01(\x0b\x32\x1a.MetricRecord.Timeinterval\x12$\n\x06values\x18\x02 \x01(\x0b\x32\x14.MetricRecord.Valuesb\x06proto3'
)




_METRICRECORD_TIMESERIESDESCRIPTOR = _descriptor.Descriptor(
  name='Timeseriesdescriptor',
  full_name='MetricRecord.Timeseriesdescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='container_name', full_name='MetricRecord.Timeseriesdescriptor.container_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='project_id', full_name='MetricRecord.Timeseriesdescriptor.project_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='location', full_name='MetricRecord.Timeseriesdescriptor.location', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cluster_name', full_name='MetricRecord.Timeseriesdescriptor.cluster_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='namespace_name', full_name='MetricRecord.Timeseriesdescriptor.namespace_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='controller_name', full_name='MetricRecord.Timeseriesdescriptor.controller_name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='controller_type', full_name='MetricRecord.Timeseriesdescriptor.controller_type', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=351,
)

_METRICRECORD_TIMEINTERVAL = _descriptor.Descriptor(
  name='Timeinterval',
  full_name='MetricRecord.Timeinterval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_time', full_name='MetricRecord.Timeinterval.start_time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='MetricRecord.Timeinterval.end_time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=405,
)

_METRICRECORD_VALUES = _descriptor.Descriptor(
  name='Values',
  full_name='MetricRecord.Values',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='int64Value', full_name='MetricRecord.Values.int64Value', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='doubleValue', full_name='MetricRecord.Values.doubleValue', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=456,
)

_METRICRECORD_POINTDATA = _descriptor.Descriptor(
  name='Pointdata',
  full_name='MetricRecord.Pointdata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeInterval', full_name='MetricRecord.Pointdata.timeInterval', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='values', full_name='MetricRecord.Pointdata.values', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=557,
)

_METRICRECORD = _descriptor.Descriptor(
  name='MetricRecord',
  full_name='MetricRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeSeriesDescriptor', full_name='MetricRecord.timeSeriesDescriptor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pointData', full_name='MetricRecord.pointData', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metricName', full_name='MetricRecord.metricName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_METRICRECORD_TIMESERIESDESCRIPTOR, _METRICRECORD_TIMEINTERVAL, _METRICRECORD_VALUES, _METRICRECORD_POINTDATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=557,
)

_METRICRECORD_TIMESERIESDESCRIPTOR.containing_type = _METRICRECORD
_METRICRECORD_TIMEINTERVAL.containing_type = _METRICRECORD
_METRICRECORD_VALUES.containing_type = _METRICRECORD
_METRICRECORD_POINTDATA.fields_by_name['timeInterval'].message_type = _METRICRECORD_TIMEINTERVAL
_METRICRECORD_POINTDATA.fields_by_name['values'].message_type = _METRICRECORD_VALUES
_METRICRECORD_POINTDATA.containing_type = _METRICRECORD
_METRICRECORD.fields_by_name['timeSeriesDescriptor'].message_type = _METRICRECORD_TIMESERIESDESCRIPTOR
_METRICRECORD.fields_by_name['pointData'].message_type = _METRICRECORD_POINTDATA
DESCRIPTOR.message_types_by_name['MetricRecord'] = _METRICRECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetricRecord = _reflection.GeneratedProtocolMessageType('MetricRecord', (_message.Message,), {

  'Timeseriesdescriptor' : _reflection.GeneratedProtocolMessageType('Timeseriesdescriptor', (_message.Message,), {
    'DESCRIPTOR' : _METRICRECORD_TIMESERIESDESCRIPTOR,
    '__module__' : 'metric_record_pb2'
    # @@protoc_insertion_point(class_scope:MetricRecord.Timeseriesdescriptor)
    })
  ,

  'Timeinterval' : _reflection.GeneratedProtocolMessageType('Timeinterval', (_message.Message,), {
    'DESCRIPTOR' : _METRICRECORD_TIMEINTERVAL,
    '__module__' : 'metric_record_pb2'
    # @@protoc_insertion_point(class_scope:MetricRecord.Timeinterval)
    })
  ,

  'Values' : _reflection.GeneratedProtocolMessageType('Values', (_message.Message,), {
    'DESCRIPTOR' : _METRICRECORD_VALUES,
    '__module__' : 'metric_record_pb2'
    # @@protoc_insertion_point(class_scope:MetricRecord.Values)
    })
  ,

  'Pointdata' : _reflection.GeneratedProtocolMessageType('Pointdata', (_message.Message,), {
    'DESCRIPTOR' : _METRICRECORD_POINTDATA,
    '__module__' : 'metric_record_pb2'
    # @@protoc_insertion_point(class_scope:MetricRecord.Pointdata)
    })
  ,
  'DESCRIPTOR' : _METRICRECORD,
  '__module__' : 'metric_record_pb2'
  # @@protoc_insertion_point(class_scope:MetricRecord)
  })
_sym_db.RegisterMessage(MetricRecord)
_sym_db.RegisterMessage(MetricRecord.Timeseriesdescriptor)
_sym_db.RegisterMessage(MetricRecord.Timeinterval)
_sym_db.RegisterMessage(MetricRecord.Values)
_sym_db.RegisterMessage(MetricRecord.Pointdata)


# @@protoc_insertion_point(module_scope)
