# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the License);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-exporter-sa
  namespace: custom-metrics
  annotations:
    iam.gke.io/gcp-service-account: svc-metric-exporter@PROJECT_ID.iam.gserviceaccount.com

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-exporter-cr
rules:
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: metrics-exporter-crb
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: metrics-exporter-cr
subjects:
- kind: ServiceAccount
  name: metrics-exporter-sa
  namespace: custom-metrics

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: metrics-exporter
  namespace: custom-metrics
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: metrics-exporter-sa
          nodeSelector:
            iam.gke.io/gke-metadata-server-enabled: "true"
          containers:
          - name: metrics-exporter
            image: REGION-docker.pkg.dev/PROJECT_ID/metric-exporter-repo/metric-exporter
            env:
              - name: DISABLEVPA
                value: "true"
          restartPolicy: OnFailure
      backoffLimit: 1

