steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/metric-exporter-repo/metric-exporter', '.' ]
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/metric-exporter-repo/metric-exporter:latest'